name: deploy on k8s

on: 
  workflow_call: 

jobs:
  deploy:
    name: helm chart update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update kustomization image
        run: |
          sed -i "s/k8s-data:.*/k8s-data:${GITHUB_SHA}/g" demo-app/values.yaml
      - name: Commit changes
        run: |
          git config user.name "anupnandeda5759"
          git config user.email "anupnandeda@gmail.com"
          git add demo-app/values.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push
          